---
- name: Install Nginx
  hosts: frontend
  become: true

  vars:
    backend_public_ip: "{{ hostvars[groups['backend'][0]]['public_ip_address'] }}"
    
  tasks:
    - name: Install NGINX
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: Enable Nginx
      ansible.builtin.service:   
        name: nginx
        state: started
        enabled: true

    - name: removing default files
      ansible.builtin.shell:
        cmd: rm -rf /usr/share/nginx/html/*

    - name: copying all frontend files      
      ansible.builtin.copy:
        src: ../../todo/frontend/
        dest: /usr/share/nginx/html/

    - name: Configure backend API URL
      ansible.builtin.template:
        src: templates/config.js.j2
        dest: /usr/share/nginx/html/config.js
    
    - name: start the nginx
      ansible.builtin.service:
        name: nginx
        state: started

   
      